# Generated by Django 3.2.4 on 2021-06-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('beginner', 'beginner'), ('intermediate', 'intermediate'), ('advanced', 'advanced')], default='', max_length=60)),
                ('courseNumber', models.IntegerField(choices=[(28, 28), (221, 221), (246, 246)], default=0)),
                ('instructorName', models.CharField(default='', max_length=60)),
                ('classDuration', models.FloatField(default=1.0)),
            ],
        ),
    ]
